### PR TITLE
Translate categories

### LINKED ISSUE #67: Category strings don't translate on website
Category tags don't translate on website, even though the categories are translated at Weblate! Please see attached screenshots.

Also, some categories are not defined at Weblate, for instance:

- Machine Learning
- Neural Network
- maybe others?

translate01

translate02

### PR DESCRIPTION
**Pull request by maltejur**
Closes #67 

All categories can now be translated via [weblate](https://hosted.weblate.org/projects/TheAlgorithms/categories/).

### CODE REVIEW

**Comment by maltejur** [comment]
#### 📝Changed routes:


| [**/404**](https://website-19ptpi0hn-thealgorithms.vercel.app/404) | [**/algorithm/\[algorithm\]**](https://website-19ptpi0hn-thealgorithms.vercel.app/algorithm/[algorithm]) |
|:-:|:-:|
|<a href="https://website-19ptpi0hn-thealgorithms.vercel.app/404">Screenshot of /404</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/pMQeNSO4msvoyv2goZWQ-oZYE_9CAWjfXaGDz0ZzqdbXId4EEaxTjLiPzXRhbDJeDD-rBFXqfWdIxAtk8omDrg.png">(view full size)</a> |<a href="https://website-19ptpi0hn-thealgorithms.vercel.app/algorithm/[algorithm]">Screenshot of /algorithm/[algorithm]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/1lwnd0sMAa6U_WdJ2p9Da0v7xxAE38-Ho6tVZYP1eAHMpI46FEpq2Dj0U90cJoUl9H8d2_eJ3Nsam0FGmC3IlQ.png">(view full size)</a> |



| [**/all**](https://website-19ptpi0hn-thealgorithms.vercel.app/all) | [**/category/\[category\]**](https://website-19ptpi0hn-thealgorithms.vercel.app/category/[category]) |
|:-:|:-:|
|<a href="https://website-19ptpi0hn-thealgorithms.vercel.app/all">Screenshot of /all</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/Igtb96ZvD7dQS6CZfKRFVj4sAW1GCDLWdUJ6ZzUCdKC_R5xH9igpWgWEwcfWvRcTEmfDaxx-uT63Kf_DhobFlQ.png">(view full size)</a> |<a href="https://website-19ptpi0hn-thealgorithms.vercel.app/category/[category]">Screenshot of /category/[category]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/UZS5L0AVee88bXqM6RWyW8aRJl5XzTbnWiLItNmP8SmwOvRu9NXTh7y1xX1MsNlRUFr5GM2h66Bj_Jc-eQ23Uw.png">(view full size)</a> |



| [**/**](https://website-19ptpi0hn-thealgorithms.vercel.app/) | [**/language/\[language\]**](https://website-19ptpi0hn-thealgorithms.vercel.app/language/[language]) |
|:-:|:-:|
|<a href="https://website-19ptpi0hn-thealgorithms.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/IRyhP7UnFEumaDw0tykego2-IBowi_Ie4J_h3VEnKaGE0Fxshawwz_TSR1cjodWaso_Qo27AwbzqMs1tlwtTrQ.png">(view full size)</a> |<a href="https://website-19ptpi0hn-thealgorithms.vercel.app/language/[language]">Screenshot of /language/[language]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/zatFvstUhe1qE-Kc2PO2o8OMxuc6fXWBCi3r2t4sLhFHEA6rHxMhzVJsyreaQt8dpb_XrKkS89p0DAa1diyfEQ.png">(view full size)</a> |



And 1 other route:
- [**/search**](https://website-19ptpi0hn-thealgorithms.vercel.app/search)



Commit f6cd2102adc4e62dd5ae968cb97f1027075355ae (https://website-19ptpi0hn-thealgorithms.vercel.app).

**Review by Panquesito7 — COMMENTED** [review]
Why remove the `devicon` submodule? 🤔

**Comment by maltejur** [comment]
> Why remove the `devicon` submodule? thinking

Because it isn't used

**Review by Panquesito7 — DISMISSED** [review]
Good work, @maltejur! Everything seems to be working fine for me. 👍 🎉

**Review by Panquesito7 — DISMISSED** [review]

**Pull request merged**
