### PR TITLE
feat: Translation support and minor improvements for #71

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Translation support and minor improvements for #71

### CODE REVIEW

**Comment by maltejur** [comment]
I don't have much time right now, I will work on this in a few days

**Comment by Panquesito7** [comment]
> I don't have much time right now

For me, this is working fine, I'll merge the PR.

**Comment by maltejur** [comment]
I used the `<Link>` instead of `<a>`, because that gets styled correctly. If you go on dark mode, the color of the `<a>` is too dark.

**Review by maltejur — CHANGES_REQUESTED** [review]
I used the `<Link>` instead of `<a>` originaly, because that gets styled correctly. If you go on dark mode, the color of the `<a>` is too dark.

**Comment by maltejur** [comment]
#### 📝Changed routes:


| [**/**](https://website-cwi34llu4-thealgorithms.vercel.app/) |
|:-:|
|<a href="https://website-cwi34llu4-thealgorithms.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/9CamqKj7WHDp6f2b-O7iGSiUrqDl2gcDQX_4wBovpbFltLots086Do_UV4PdHpdwiqqBoNur20cc_3X7a8rPhg.png">(view full size)</a> |







Commit 5fcd9440e4d2f7c662d57f06dacf028e24d73a6d (https://website-cwi34llu4-thealgorithms.vercel.app).

**Review by maltejur — APPROVED** [review]

**Pull request merged**
