### PR TITLE
Python Code Playground

### LINKED ISSUE #96: Add more Programming Languages to Code Playground
Idea is to add a code playground section in code view frame. Once user clicks on `Play` button, user should be able to modify a virtual instance of current code and should be able to play around with that code by running the modified code on the very same page. This will create a beautiful learning experince.

- [ ] C (High Priority)
- [ ] C++ (High Priority)
- [ ] Java (High Priority)
- [x] Python (High Priority)
- [ ] Javascript (High Priority)
- [ ] Rust (Medium Priority)
- [ ] Golang (Medium Priority)
- [ ] MATLAB (Low Priority)
- [ ]  Ruby (Low Priority)
- [ ] C# (High Priority)
- [ ] Swift (Medium Priority)
- [ ] Jupyter (Medium Priority)
- [ ] Julia (Low Priority)
- [ ] Kotlin (High Priority)
- [ ] R (Medium Priority)
- [ ] OCaml (Low Priority)
- [ ] Elm (Low Priority)
- [ ] Dart (Medium Priority)
- [ ] Haskell (Medium Priority)
- [ ] Elixir (Low Priority)
- [ ] Clojure (Low Priority)
- [ ] F# (Low Priority)
- [ ] Scala (Low Priority)
- [ ] PHP (Low Priority)
- [ ] AArch-64 Assembly (Low Priority)

### PR DESCRIPTION
**Pull request by maltejur**
Closes #96 

**What change does this pull request introduce?**

Add a "code playground" to test out the python algorithms and also modify them. The code playground works with [pyodide](https://pyodide.org/en/stable/) and runs completely in the browser.

**TODO**

- [x] Add translations
- [x] Implement light/dark mode
- [x] Fix some error messages

**Screenshots**

Screenshot_20210831_183003

Screenshot 2021-09-02 at 18-14-30 Code Playground - The Algorithms

### CODE REVIEW

**Review by ayaankhan98 — COMMENTED** [review]
Try doing it using firepad editor, it has support for multiple lanaguges.

**Comment by maltejur** [comment]
Do you mean you want online collaboration? Firepad uses, from what i can see, the codemirror editor and adds online collaboration. I think that the monacco editor (the one I am currently using and the one that is used by visual studio code) looks much more modern and seems to have more features.

**Comment by ayaankhan98** [comment]
> Do you mean you want online collaboration? Firepad uses, from what i can see, the codemirror editor and adds online collaboration. I think that the monacco editor (the one I am currently using and the one that is used by visual studio code) looks much more modern and seems to have more features.

No don't setup multiple user, just instantiate it for single user when user click on `Try this code` button. Yes Monaco has more features. You can use Monaco instead of firepad.

**Comment by maltejur** [comment]
Ah no, I have already implemented it. You can try it out here https://website-git-codeplayground-thealgorithms.vercel.app/

**Comment by ayaankhan98** [comment]
> Ah no, I have already implemented it. You can try it out here https://website-git-codeplayground-thealgorithms.vercel.app/

Ohh! My bad. I didn't read this part of your previous comment `(the one I am currently using and the one that is used by visual studio code)` 

> You can try it out here https://website-git-codeplayground-thealgorithms.vercel.app/

I already tested this dully and it looks good to me. Try adding it for more languages.

**Comment by maltejur** [comment]
> Try adding it for more languages.

Uhh that is pretty hard. I was lucky I found the pyodide library for python and even then it wasn't exactly easy to integrate. I'd argue that because python is the biggest repository with the most algorithms and most people understanding python, it is enough for now. But in the future, I hope I can add more languages.

**Comment by ayaankhan98** [comment]
> > Try adding it for more languages.
> 
> Uhh that is pretty hard. I was lucky I found the pyodide library for python and even then it wasn't exactly easy to integrate. I'd argue that because python is the biggest repository with the most algorithms and most people understanding python, it is enough for now. But in the future, I hope I can add more languages.

No problem, This looks good to me.

**Review by ayaankhan98 — COMMENTED** [review]
Great work @maltejur :+1: 
would be nice to have a button to exit the playground mode, currently there is nothing we just have to go with browser back button.
Screenshot_20210903_001533

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Awesome work, @maltejur! I liked it a lot. 😄👍
I just think we should print the text used to explain what the input is going to be used for. For example: in this case, the text `Enter numbers separated by comma:` should appear. I got confused at first because I didn't know why that appeared. 😅

image

**Comment by maltejur** [comment]
Yes that is quite confusing, but that is a issue with pyodide (https://github.com/pyodide/pyodide/issues/758). I'll try to find a way arround it, but this has to do it for now.

**Comment by Panquesito7** [comment]
> Yes that is quite confusing, but that is a issue with pyodide ([pyodide/pyodide#758](https://github.com/pyodide/pyodide/issues/758)). I'll try to find a way arround it, but this has to do it for now.

What if you try to do what they did here? https://github.com/pyodide/pyodide/issues/758#issuecomment-696418449

**Comment by maltejur** [comment]
How did I not see that? It should work now

**Review by Panquesito7 — APPROVED** [review]
Working well, although some algorithms like Knight Tour fail. Everything else is looking perfect! Awesome work, @maltejur! Thank you! 😄👍🎉

**Comment by raklaptudirm** [comment]
Languages like `golang` and `rust` have their own code playgrounds, which are bound to have a public api i believe.

From the `go playground` about section:
> The playground service is used by more than just the official Go project (Go by Example is one other instance) and we are happy for you to use it on your own site. All we ask is that you contact us first (note this is a public mailing list), use a unique user agent in your requests (so we can identify you), and that your service is of benefit to the Go community.

The `rust playground` source code [here](https://github.com/integer32llc/rust-playground).

Taking inputs can be a problem with these services though.

**Pull request merged**
