### PR TITLE
Remove CodeQL and replace it with tsc and eslint

### PR DESCRIPTION
**Pull request by maltejur**

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
What if we keep both? CodeQL is still good IMO.

**Comment by maltejur** [comment]
But as you can see on other pull requests, CodeQL is broken sometimes https://github.com/TheAlgorithms/website/pull/76, https://github.com/TheAlgorithms/website/pull/70

**Comment by Panquesito7** [comment]
I'm guessing CodeQL is broken in the #70 PR because it is a draft PR, or it has merge conflicts. I'm not really sure why it was broken in the #76 PR, though. I think it's because Dependabot doesn't have access to the repository or something similar according to what the error said.

**Comment by maltejur** [comment]
In the background, CodeQL also just runs eslint. So this new approach is just making it work better

**Comment by Panquesito7** [comment]
> In the background, CodeQL also just runs eslint. So this new approach is just making it work better

Oh, alright. You can merge it if you want. 🙂

**Pull request merged**
