### PR TITLE
refactor: close button in code preview frame

### LINKED ISSUE #93: Code display Iframe close button issue
### Description
There are two buttons on the top right of iframe `View on Github` and another is `Close`. Both buttons are disimilar in UI perspective. would not it be nice if we make them a look a bit similar such as that border around `Close` button is not matching with another button. 

button issue

### PR DESCRIPTION
**Pull request by ayaankhan98**
Closes #93 

**What change does this pull request introduce?**
Improvement in Close button

**Screenshots**\
Screenshot_20210611_010830

**Checklist**

- [ ] I worked on a branch other than `main`.
- [ ] My branch is up-to-date with the Upstream `main` branch.
- [ ] I have fixed potential errors using `yarn lint`.
- [ ] I ran `yarn build` to check everything still builds successfully.

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
LGTM. Thanks, @ayaankhan98! 😄 👍

**Comment by maltejur** [comment]
It definitely looks nicer visually, but I think we need to still make it more visible, so that users won't just not see the button and think the page is stuck (I know this is a issue because when we had the button styled the same as then `View on Github` button before, @Panquesito7 didn't find the button at first)

**Comment by ayaankhan98** [comment]
> but I think we need to still make it more visible

I think button color should be material secondary.

**Comment by maltejur** [comment]
> I think button color should be material secondary.

Isn't that pink. I don't think that would fit in the color scheme.

**Comment by Panquesito7** [comment]
> so that users won't just see the button and think the page is stuck

I suggest the code should like "close" when you click outside the code. I hope I get to understand. 🙂

**Comment by maltejur** [comment]
Yeah that sound like a great idea

**Comment by Panquesito7** [comment]
> Yeah that sound like a great idea

Should I work on it or will you work on it?

**Comment by ayaankhan98** [comment]
> > Yeah that sound like a great idea
> 
> Should I work on it or will you work on it?

sure, if you wish you can.

**Pull request closed without merging**
