### PR TITLE
feat: Update Vercel banner in the footer

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Update Vercel banner in the footer.

[Powered by Vercel](https://vercel.com?utm_source=thealgorithms&utm_campaign=oss)

Banner taken out from `README.md`.

### CODE REVIEW

**Comment by Panquesito7** [comment]
Not sure why the Vercel checks haven't run yet...Weird.
Anyways I have added this repository in the [Vercel](https://vercel.com/thealgorithms/website/settings/git) settings.

Hope that works. 🙂

**Comment by maltejur** [comment]
> Not sure why the Vercel checks haven't run yet...Weird.
> Anyways I have added this repository in the [Vercel](https://vercel.com/thealgorithms/website/settings/git) settings.

Have you done that before or after opening the pr?

*Edit:* 
On the other pr, the preview deployment worked perfectly fine, so I guess it works

**Comment by maltejur** [comment]
Here's a manual preview deployment of the pr https://website-jdwqy697s-thealgorithms.vercel.app/

I've also put in this badge at first, but I think the white text fits more in with the page. What do you think looks better?

**Comment by Panquesito7** [comment]
> What do you think looks better?

For me, the one in the first comment looks better than the other one. 🙂

**Review by Panquesito7 — COMMENTED** [review]
I think this can be merged.

**Review by maltejur — APPROVED** [review]

**Pull request merged**
