### PR TITLE
add LiveCodes as playground and test runner

### LINKED ISSUE #264: [OTHER]: Online client-side playground with test runner
### What would you like to share?

Great project, thank you!

I want to share with you an online, client-side playground that I have created for the algorithms in this project. It imports code implementations from the repo and runs the tests.

Demo: https://hatemhosny.github.io/thealgorithms-javascript

Code can be edited in the code editor (using Monaco on desktop and CodeMirror6 on mobile). The code runs in the browser (in a sandboxed iframe), with no need for a backend. Test runner is available, which runs the tests in the browser using Jest.

Direct links to a specific algorithm are supported.  When a new algorithm is selected from the dropdown menu, the URL querystring parameter `algorithm` is changed to the selected one. This URL can be shared and the selected algorithm will be loaded by default. e.g. https://hatemhosny.github.io/thealgorithms-javascript/?algorithm=Recursive/Factorial

Clear Links to your project are added (in the project GitHub repo, the deployed page and in imported code) as indicators for the source of the implementations and tests.

The source code for my project can be found here: https://github.com/hatemhosny/thealgorithms-javascript. 

This playground is built using [LiveCodes](https://livecodes.io/), a [feature-rich](https://livecodes.io/docs/features/), [open-source](https://github.com/live-codes/livecodes), [client-side](https://livecodes.io/docs/why#client-side) code playground that supports [80+ languages/frameworks](https://livecodes.io/docs/why#language-support). The playground is [embedded](https://livecodes.io/docs/features/embeds) in the page using LiveCodes [SDK](https://livecodes.io/docs/sdk).

Disclosure: I am the author of LiveCodes.

I'm just letting you know about the project and thanking you for such a great resource. If you think [LiveCodes](https://livecodes.io/) can be useful in the official website or for direct links to run samples in the repo, please let me know. If you want to change the UI of the playground, [LiveCodes SDK](https://livecodes.io/docs/sdk) has a [headless mode](https://livecodes.io/docs/sdk/headless) which can give you full control over the UI, maintaining the ability to communicate with the playground using various [SDK methods](https://livecodes.io/docs/sdk/js-ts#sdk-methods) (e.g. for running code or tests and getting console output and test results). In addition, if you require extra features, I'm open for discussion.

Of course, feel free to close this issue whenever you feel suitable.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hatemhosny**
Closes #264

**What change does this pull request introduce?**

This PR adds [LiveCodes](https://livecodes.io/) as a code playground and test runner for some of the supported languages (currently JavaScript, TypeScript, Python and R). (please see #264)

**Summary of approach**
Depending on the selected language, either LiveCodes playground or the original playground editor is loaded.  
When loading the algorithm code, test code is also loaded in relevant repos (currently JavaScript and TypeScript).  
In Python, doctests are run using Pyodide and the results are shown in the integrated console.

**Still work-in-progress**
If you approve this approach, may be you want to remove the original Pyodide code runner.  
Still switching themes (dark/light themes) is not implemented. However, this should be available soon.

Please let me know what you think.

By the way, I noticed that no R code is currently fetched, in addition to some other issues I noticed in `fetch-algorithms` script. May be I can add a separate PR for that.

**Screenshots**

JS
thealgorithms-livecodes

Python
thealgorithms-livecodes-py

**Checklist**

- [x] I worked on a branch other than `main`.
- [x] My branch is up-to-date with the Upstream `main` branch.
- [x] I have fixed potential errors using `yarn lint`.
- [x] I ran `yarn build` to check everything still builds successfully.

### CODE REVIEW

**Comment by maltejur** [comment]
Thanks! Is there any way to make user input work? If I comment out the input code on the [binary search](https://website-git-fork-hatemhosny-livecodes-thealgorithms.vercel.app/algorithm/binary-search), it throws the following error:

Screenshot_20231017_000147

With the existing playground powered by pyodide, this works as expected:

image

[This](https://github.com/TheAlgorithms/website/blob/b811e1eb06e23e0f32647e841fb3469a2f7147ab/lib/playground/pythonCodeRunner.ts#L33) is the code I used to make that work, I remember it was a bit hacky. Maybe that helps.

**Comment by hatemhosny** [comment]
> Is there any way to make user input work?

@maltejur It works now :)

**Comment by hatemhosny** [comment]
Updates:
- Python input works
- R works
- Added Ruby


Python input
Screenshot (73)

Python Result
Screenshot (74)

R
Screenshot (72)

Ruby input
Screenshot (70)

Ruby result
Screenshot (71)

**Review by maltejur — DISMISSED** [review]
Thanks, looks great! Once you are ready I am happy to merge this.

One small nitpick: the autorunning of the code after ~2s of inactivity kind of clashes with the user input prompts. I am not sure though what the best solution for that would be.

**Comment by hatemhosny** [comment]
added Lua:

Screenshot (76)

**Comment by hatemhosny** [comment]
> Thanks, looks great! Once you are ready I am happy to merge this.

Thanks @maltejur , I have a few things to tidy up. I will let you know when I'm ready.
 
> One small nitpick: the autorunning of the code after ~2s of inactivity kind of clashes with the user input prompts. I am not sure though what the best solution for that would be.

The default behavior is that the code autoruns after 1.5 sec. This can be configured for longer or shorter delays. 
Currently, I have disabled autorunning. So, now users will have to click the run button or use the keyboard shortcut (Shift+Enter) to run the code. Please check if you think this is better or shall I re-enable the autorun?

I want your opinion about a few things:

- Now the original python runner (Pyodide) is no longer in use. Shall I remove it, or do I leave it for a later PR?
- Regarding language support:
  - some languages are not supported in LiveCodes (e.g. Java, Swift, Rust):
    these still use the original playground (with piston code runner)
  - some languages are supported in LiveCodes but have better performance in the original playground (e.g. C++, Julia):
    these use the original playground
  - some languages are better in LiveCodes + can run tests: Python, JavaScript, TypeScript, R, Ruby, Lua, Jupyter
    these use LiveCodes
  - some languages are comparable in both (e.g. PHP, Go, C). 
    I cannot run their tests, mostly because that needs external runners or asks for user input. However, this is similar to the behavior of piston runner. **what shall I do with these?** (the advantage I see for LiveCodes is better support for mobile devices)

  I still have some more languages to explore

**Comment by hatemhosny** [comment]
added Jupyter

Instead of displaying the notebook JSON, Python code is extracted from JSON and run using Pyodide

Pandas
Screenshot (78)

Matplotlib
Screenshot (77)

**Comment by hatemhosny** [comment]
changing themes now works

light theme
Screenshot (81)

dark theme
Screenshot (82)

**Comment by hatemhosny** [comment]
hi @maltejur 

I believe the PR is ready now for review.

I would also value your opinion about [these inquiries](https://github.com/TheAlgorithms/website/pull/269#issuecomment-1773344542).

Thank you

**Review by maltejur — DISMISSED** [review]
Thanks a lot for the work you did!

> The default behavior is that the code autoruns after 1.5 sec. This can be configured for longer or shorter delays.
Currently, I have disabled autorunning. So, now users will have to click the run button or use the keyboard shortcut (Shift+Enter) to run the code. Please check if you think this is better or shall I re-enable the autorun?

Having it on a manual run button sounds like the best solution to be, so I would say just keep it as it is right now.

> Now the original python runner (Pyodide) is no longer in use. Shall I remove it, or do I leave it for a later PR?

Sure, go ahead.

> some languages are comparable in both (e.g. PHP, Go, C).
> I cannot run their tests, mostly because that needs external runners or asks for user input. However, this is similar to the behavior of piston runner. what shall I do with these? (the advantage I see for LiveCodes is better support for mobile devices)

I think we can go with LiveCodes with those if you think that is better.

The rest looks good to me, I can merge the PR once you are ready.

**Comment by hatemhosny** [comment]
use LiveCodes for PHP, Go and C

these may need to manually add some code to run the algorithm code

Examples:

PHP
Screenshot (83)

Go
Screenshot (85)

C
Screenshot (84)

**Comment by hatemhosny** [comment]
@maltejur 
I think I'm ready now if you can have a look.
Thank you.

**Review by maltejur — APPROVED** [review]
Thanks a loot, looks good to me!

**Comment by hatemhosny** [comment]
@maltejur 
I noticed the production deployment for this failed. I cannot see the logs.
Is there anything I need to fix on my end?

**Comment by maltejur** [comment]
That has nothing to do with your changes, it seems like there are ratelimits by GitHub which makes the fetching of some stuff fail.

> RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID CB38:0F1F:5C9B91:BFB3B1:6546C520.

I'll try to rebuilt again tomorrow.

**Pull request merged**
