### PR TITLE
[Add] Nim Repository

### LINKED ISSUE #6: Add to the algorithms website
At some point we should add this to main website, for a ref PR we can see how zig was added: https://github.com/TheAlgorithms/website/pull/225/files

the only issue I see is that of highlighting, I imagine the two will not have Nim support (zig was highlighted as rust…)

### PR DESCRIPTION
**Pull request by dlesnoff**
Fix https://github.com/TheAlgorithms/Nim/issues/6

**What change does this pull request introduce?**
Add Nim to the website.
https://www.nim-lang.org/

**Screenshots**

**Checklist**

- [x] I worked on a branch other than `main`.
- [x] My branch is up-to-date with the Upstream `main` branch.

I am not familiar with yarn. 
I am waiting for fetch-algorithms.ts ending.
- [ ] I have fixed potential errors using `yarn lint`.
There were 3 errors already present in preceding PRs. I do not know how to fix them and they are unrelated to my files.
- [x] I ran `yarn build` to check everything still builds successfully.

### CODE REVIEW

**Comment by dlesnoff** [comment]
caniuse-lite must be updated.
Stars next to language repositories are equal to 0 (error: API limit exceeded).
Nim logo is incorrect (it is a little crown).

**Comment by maltejur** [comment]
Thanks for the PR.

Devicon (what we use for the icons) already [seems to have](https://github.com/devicons/devicon/pull/1113) the nim icon, but they haven't released a new version in a year. I've switched the url used for the icons to use the development branch of devicon, that way we get the nim icon.

The issue with the 0 stars should not happen on the actual website, we use a api key there. And I will fix the other issues (caniuse,linting errors) outside of this PR.

**Review by maltejur — APPROVED** [review]

**Comment by dlesnoff** [comment]
Nim now appears on the website, but the logo still does not appear correctly. It is still written Nim in plain text instead of showing the crown.

**Comment by maltejur** [comment]
Hm, works for me:

image

**Comment by maltejur** [comment]
Ah its only a issue in the dark mode because there is no `plain` nim devicon, you still have to use the `original` one. I've pushed the fix.

**Comment by dlesnoff** [comment]
I got it. I am in dark mode, and it does not have the dark mode version of the logo.
Thanks.

**Pull request merged**
