### PR TITLE
Add CSS effects in the `algorithmCard`

### LINKED ISSUE #82: Added Effects to Featured Algorithms and Top algorithms Box to enhance UI more
I would like to work on CSS part of box so that to make more UI interactive . Kindly assign me this issue and I will work on this .

### PR DESCRIPTION
**Pull request by Panquesito7**
Closes #82

**What change does this pull request introduce?**

- Add CSS effects to make the UI more interactive in the `algorithmCard`.
  - Thanks to @Anmolreshi for the idea and suggestion!

**Screenshots**

image
image

**Checklist**

- [x] I worked on a branch other than `main`.
- [x] My branch is up-to-date with the Upstream `main` branch.
- [x] I have fixed potential errors using `yarn lint`.
- [x] I ran `yarn build` to check everything still builds successfully.

### CODE REVIEW

**Comment by Anmolreshi** [comment]
Great !

**Comment by maltejur** [comment]
I am not sue if changing the background color on hover is the best way more interactive. I would instead suggest to increase the shadow of the cards on hover.

**Review by ayaankhan98 — COMMENTED** [review]
just add a little bit of elevation on hover and also get rid of bottom line on link hover.

**Review by Panquesito7 — COMMENTED** [review]
Looks good. 👍

**Review by ayaankhan98 — COMMENTED** [review]
Screenshot_20210606_202522
Still there is underline on link hover

**Comment by maltejur** [comment]
Is that a bad thing?

**Comment by ayaankhan98** [comment]
> Is that a bad thing?

No, i didn't said that it's bad. What i was trying to say that at some places there is no underline on links but at these places there is underline. Shouldn't we a bit consistent with UI?

**Comment by ayaankhan98** [comment]
> just add a little bit of elevation on hover and also get rid of bottom line on link hover.

I quoted it here to remove bottom lines on link, so i thought that this was considered at some places but not at other which directed me to think that may be @Panquesito7 has forgotton to change it at all places that's why i pointed it out.

There is no problem if you want to keep it as it is. I am okay with that.

**Review by Panquesito7 — COMMENTED** [review]
For me, it looks good, can be merged. 👍

**Comment by Anmolreshi** [comment]
Great work ! Finally its merged

**Pull request merged**
