### PR TITLE
feat: switch to alternative code preview with language select

### LINKED ISSUE #20: Default preview of algorithms in Python
If we search and choose any algorithm the default preview code is of python, if we click on the language icons provided below the code we will be redirect to the specific repository. Wouldn't it be nice if instead of redirecting to the repository just show the code in choosed language in the same way as it was for Python.

### PR DESCRIPTION
**Pull request by maltejur**
Closes #20.

Screenshot 2021-03-02 154643

### TODO
- [x] Improve how it looks on mobile
- [x] Add full screen button
- [x] Jupyter edgecase

### CODE REVIEW

**Review by ayaankhan98 — COMMENTED** [review]
This is looking good to me.

**Comment by maltejur** [comment]
I am not quite happy with how it looks on mobile, I will try to do something there

Screenshot 2021-03-02 174831

**Comment by ayaankhan98** [comment]
> I am not quite happy with how it looks on mobile, I will try to do something there
> 
> Screenshot 2021-03-02 174831

yes, that scrolling part is not looking good in mobile view.

I would be nice if you provide full screen icon near the `view on github` icon in the top right corner. This will enlarge the iframe with code and will look more user friendly. isn't?

**Comment by ayaankhan98** [comment]
For desktop view also it will improve the reading experience of user. Also the font size is quite small in the frame, and is very inconvinient for reading purposes.

**Comment by maltejur** [comment]
Another issue: Right now, the code for the jupyter algorithms gets hidden, because it already gets rendered below as an explanation.
Example https://website-git-switchcodepreviewlang-thealgorithms.vercel.app/algorithm/a-simple-gan

**Comment by maltejur** [comment]
This is just a small technical preview how the mobile fullscreen thing would work. I will probably rewrite the whole thing.
https://website-git-switchcodepreviewlang-thealgorithms.vercel.app

**Review by ayaankhan98 — COMMENTED** [review]
Capture

View on github link is overlapping with code

**Review by ayaankhan98 — DISMISSED** [review]
Great work @maltejur, LGTM.

**Comment by maltejur** [comment]
@Panquesito7 what do you think?

**Review by Panquesito7 — COMMENTED** [review]
Don't know too much about JavaScript/TypeScript. All looks good though. 😄
~I found one bug though: when you change the language, you can no longer scroll down or up: you can only scroll down in the code.~ There's the `Close` button, so this is no longer needed.

**Comment by maltejur** [comment]
Ah seems I have found the same bug 😄

**Review by Panquesito7 — APPROVED** [review]
Amazing work, @maltejur! Looks pretty nice. Thank you! 👍 🎉

**Pull request merged**
