### PR TITLE
Visual Betterments and Improvements

### PR DESCRIPTION
**Pull request by SparkScratch-P**
**The Algorhytms logo is a  superb and techie one! So, I felt l must animate it to look better, and also the 'Official Website' was in small letters, I capitalized the Initials. Now it looks better!**

**Checklist**

- [x] I worked on a branch other than `main`.
- [x] My branch is up-to-date with the Upstream `main` branch.
- [x] I have fixed potential errors using `yarn lint`.
- [x] I ran `yarn build` to check everything still builds successfully.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/website/pull/150"></a>

### CODE REVIEW

**Review by Panquesito7 — DISMISSED** [review]
Amazing! 🚀 Thanks for your contribution! 😄👍

**Comment by SparkScratch-P** [comment]
## Well, with this commit, may I be a member of the organization, please!? 
 I am eager to join it!

**Comment by SparkScratch-P** [comment]
Is it merged? where do I see the changes?

**Review by maltejur — CHANGES_REQUESTED** [review]
Hmm, it stays completely white for a long time without anything happening.

Also, the background is kind of off. It doesn't have the same color as GitHub:
Screenshot_20220119_202926
That is even more a problem in the dark theme
Screenshot_20220119_202947
So a transparent background would be nice

**Comment by SparkScratch-P** [comment]
Sure, I will try one, Gonna be a difficult task, still, I will try to give it!

ANd one more, I have edited on the Main branch, should i keep doing it there, or open a new branch from main? Can u pls say?

**Comment by Panquesito7** [comment]
> Sure, I will try one, Gonna be a difficult task, still, I will try to give it!
> 
> ANd one more, I have edited on the Main branch, should i keep doing it there, or open a new branch from main? Can u pls say?

It's good as-is, thanks. 🙂

**Comment by SparkScratch-P** [comment]
> > Sure, I will try one, Gonna be a difficult task, still, I will try to give it!
> > ANd one more, I have edited on the Main branch, should i keep doing it there, or open a new branch from main? Can u pls say?
> 
> It's good as-is, thanks. 🙂


Hmm, I would implement it as soon as possible!

imageedit_3_5171240699

**Comment by SparkScratch-P** [comment]
## Yes, done! Edited! Now it is, I think read to be merged!

## Can I pls be a member of The-Algorithms? I am eager to be one!

**Comment by SparkScratch-P** [comment]
## Well, I have made an animated logo and uploaded it to the `public` directory. It would look great if someone changes all such logos to animated ones.

**Comment by SparkScratch-P** [comment]
### Well; I am eager to see it merged, and yes, I wanna join this organization!

**Comment by maltejur** [comment]
Thanks for removing the white background! As I already said, there is still a lot of time at the start of the gif where nothing happens, could you maybe also remove that?

Also, I don't think I would replace the logo everywhere. Since the gif is a lot bigger than the original, the load time would be increased drastically. Also I doubt that it would look in places where the logo is pretty small. So you can remove the logo from the `public` folder and just drag-and-drop it into the markdown editor in github to upload it there.

And about the organization, I am not an admin but I think you have to be a long-term contributor to get into the organization.

**Comment by SparkScratch-P** [comment]
> Thanks for removing the white background! As I already said, there is still a lot of time at the start of the gif where nothing happens, could you maybe also remove that?

 Ok, sure, I Will!

> 
> Also, I don't think I would replace the logo everywhere. Since the gif is a lot bigger than the original, the load time would be increased drastically. Also, I doubt that it would look in places where the logo is pretty small. So you can remove the logo from the `public` folder and just drag-and-drop it into the markdown editor in GitHub to upload it there.

Ok, I am doing tht; but I feel, it looks good and animated, so it can still be replaced at some points- at least some points on the website; and some other places. I am doing as u said now, but pls see to it if some more can be replaced. I fI am allowed to, pls say me.

> 
> And about the organization, I am not an admin but I think you have to be a long-term contributor to get into the organization.

I want to be one; ok sure. Thanks for your answer.

**Comment by SparkScratch-P** [comment]
## Check if the time gap is ok or not! Then I will finalize, make it transparent, and upload it

**Comment by SparkScratch-P** [comment]
## Check if the time gap is ok or not! Then I will finalize, make it transparent, and upload it

**Comment by SparkScratch-P** [comment]
## Check if the time gap is ok or not! Then I will finalize, make it transparent, and upload it

**Comment by SparkScratch-P** [comment]
## Should I still reduce the time? Or, It's fine!?

**Comment by Panquesito7** [comment]
> ## Check if the time gap is ok or not! Then I will finalize, make it transparent, and upload it
> 

LGTM 👍 @maltejur.

**Comment by maltejur** [comment]
Yeah that looks good. I will merge it once the background is transparent again. Thanks!

**Comment by SparkScratch-P** [comment]
Ok, Bro! I will do it ASAP!

**Comment by SparkScratch-P** [comment]
## Done! I think It's ready to merge now! I have just dragged and dropped the file on the Readme. But I feel, it would look as good if they are replaced and put at many other places. Please see to it if possible! 

## Thank You

**Review by Panquesito7 — COMMENTED** [review]
In the end, it looks white; I think it should disappear completely 😅 do not use black color, just make it disappear, otherwise there'll be problems with light mode 😅 Let us know if you need any help! Thanks. 😃

**Comment by SparkScratch-P** [comment]
> In the end, it looks white; I think it should disappear completely 😅 do not use black color, just make it disappear, otherwise there'll be problems with light mode 😅 Let us know if you need any help! Thanks. 😃

I have not used black color anywhere? Where do u see it? See at light mode, there's no problem, I think so. Pls check out and say. Actually, I am not getting any background transparenting converter that works that well!

**Comment by Panquesito7** [comment]
> > In the end, it looks white; I think it should disappear completely 😅 do not use black color, just make it disappear, otherwise there'll be problems with light mode 😅 Let us know if you need any help! Thanks. 😃
> 
> I have not used black color anywhere? Where do u see it? See at light mode, there's no problem, I think so. Pls check out and say. Actually, I am not getting any background transparenting converter that works that well!

In the end, the logo becomes white. Shouldn't it totally disappear? 🤔

**Comment by SparkScratch-P** [comment]
> > > In the end, it looks white; I think it should disappear completely 😅 do not use black color, just make it disappear, otherwise there'll be problems with light mode 😅 Let us know if you need any help! Thanks. 😃
> > 
> > 
> > I have not used black color anywhere? Where do u see it? See at light mode, there's no problem, I think so. Pls check out and say. Actually, I am not getting any background transparenting converter that works that well!
> 
> In the end, the logo becomes white. Shouldn't it totally disappear? 🤔

Not Necessary... It's looking cool here, right? Still, that is better, so try it if u can do that..if I can do that change in the future... i will add later... feel free to emrge now..i will be on it!

**Review by maltejur — APPROVED** [review]
Thanks!

**Comment by SparkScratch-P** [comment]
# I am glad to be merged!

**Pull request merged**
