### PR TITLE
Improve languages list

### PR DESCRIPTION
**Pull request by maltejur**
See #86 
soiubgouiasb

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Looks good, but on mobile, AArch 64 Assembly looks too long; and its stars are not well-displayed.

**Comment by maltejur** [comment]
#### 📝Changed routes:


| [**/**](https://website-e2are3gb6-thealgorithms.vercel.app/) |
|:-:|
|<a href="https://website-e2are3gb6-thealgorithms.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/RQC6zKK041Fe2z5w660m8-mSvFRpJBOtZ-Xma9vVml5RDBqAKv1KeWe1fkHWmA4BOcMzT1dNuuRW1UexnqVx7Q.png">(view full size)</a> |







Commit 65325c22a81dbd3654a878ff7ef60162bfa56539 (https://website-e2are3gb6-thealgorithms.vercel.app).

**Review by Panquesito7 — COMMENTED** [review]
Not sure if it's a good idea, but maybe it should be ordered by most stars. There should be also a filter. For example: check out the repositories with the fewest stars.

**Comment by maltejur** [comment]
Do you mean something like this @Panquesito7 ?

**Review by Panquesito7 — APPROVED** [review]
Looks good. Good work, @maltejur. Thanks! 👍 🎉

**Review by ayaankhan98 — APPROVED** [review]
Looks better than earlier

**Pull request merged**
