### PR TITLE
add contributors

### LINKED ISSUE #27: Add contributors to algorithm page
A good idea would be to include contibutors of the code on the page, like github does. Example:
Screenshot 2021-03-19 200721

### PR DESCRIPTION
**Pull request by maltejur**
Closes #27 

How it looks will still change

Screenshot_20210527_192201

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
I tried to add `/contributors` at the end of the link of the page, and it didn't work. 🤔

**Comment by maltejur** [comment]
> I tried to add `/contributors` at the end of the link of the page, and it didn't work. thinking

You can see the change on a page of an algorithm

**Review by Panquesito7 — COMMENTED** [review]
Looks good, but the circles of the profile photos are very close. They should be a bit more separated IMHO.

**Comment by maltejur** [comment]
#### 📝Changed routes:


| [**/algorithm/\[algorithm\]**](https://website-oyad3247p-thealgorithms.vercel.app/algorithm/[algorithm]) |
|:-:|
|<a href="https://website-oyad3247p-thealgorithms.vercel.app/algorithm/[algorithm]">Screenshot of /algorithm/[algorithm]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/fUfBfjLk4d7J4RtYyBDy5VbrYG5yJMqCR4TGSOst4905cCkEaGc15L8EToONe3aYPxdX76QwKGNo02GXDC0JjA.png">(view full size)</a> |







Commit 19b177a546514b0a7a42434039e3b51bb7af6c91 (https://website-oyad3247p-thealgorithms.vercel.app).

**Review by Panquesito7 — COMMENTED** [review]
It'd be nice if it could open a new tab when clicking on a user's profile.

**Comment by maltejur** [comment]
Doesn't the middle mouse button work for you?

**Review by Panquesito7 — DISMISSED** [review]
Great work, @maltejur. Thank you! 👍 🎉

**Comment by maltejur** [comment]
I'll still polish it a bit, it still looks pretty rough imo

**Review by Panquesito7 — COMMENTED** [review]
Instead of using a heart, maybe we should use the GitHub logo? 🤔

**Comment by maltejur** [comment]
> Instead of using a heart, maybe we should use the GitHub logo? thinking

Good idea, I also wasn't sure about the heart

**Review by Panquesito7 — COMMENTED** [review]
Why are there some profiles without a link to their GitHub profile? 🤔

**Comment by maltejur** [comment]
I can only find the profile pictures of the people with a public email on github

**Comment by Panquesito7** [comment]
> I can only find the profile pictures of the people with a public email on GitHub

Ahh, I see. But can't you get their GitHub emails like, for example, `Panquesito7@users.noreply.github.com`?

**Comment by maltejur** [comment]
> Ahh, I see. But can't you get their GitHub emails like, for example, `Panquesito7@users.noreply.github.com`?

It it possible, but not in a way that I know of that is in the free github api quota. (Because you can't do that many direct searches)

**Comment by maltejur** [comment]
Wait the `@users.noreply.github.com` could actually work

**Comment by maltejur** [comment]
Hmm it seems to work but doesn't add that much more users with a profile picture

**Pull request merged**
