### PR TITLE
Update Malayalam Translation

### PR DESCRIPTION
**Pull request by fayasnoushad**
Add more Malayalam Translation words and sentences

**Checklist**

- [ ] I worked on a branch other than `main`.
- [x] My branch is up-to-date with the Upstream `main` branch.
- [ ] I have fixed potential errors using `yarn lint`.
- [ ] I ran `yarn build` to check everything still builds successfully.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/website/pull/143"></a>

### CODE REVIEW

**Review by nuhmanpk — APPROVED** [review]

**Review by nuhmanpk — DISMISSED** [review]

**Comment by fayasnoushad** [comment]
- Arranged languages in alphabetical order
- Changed indian flag name from `hi.svg` to `india.svg`. Because 23 official languages available in India.

**Review by maltejur — APPROVED** [review]
Thanks for the pull request! By the way, translating the strings on [Weblate](https://hosted.weblate.org/projects/TheAlgorithms/common/ml/) is a much easier experience than doing it manually.

**Comment by fayasnoushad** [comment]
> Thanks for the pull request! By the way, translating the strings on [Weblate](https://hosted.weblate.org/projects/TheAlgorithms/common/ml/) is a much easier experience than doing it manually.

How to join on this organization?

**Comment by Panquesito7** [comment]
> > Thanks for the pull request! By the way, translating the strings on [Weblate](https://hosted.weblate.org/projects/TheAlgorithms/common/ml/) is a much easier experience than doing it manually.
> 
> How to join on this organization?

Currently, there's no invite to join the organization, but feel free to contact @AnupKumarPanwar about it. 🙂

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
