### PR TITLE
Add links to edit the page at the bottom of an algorithm page

### PR DESCRIPTION
**Pull request by maltejur**
~~Still needs to be translated~~

### CODE REVIEW

**Comment by maltejur** [comment]
#### 📝Changed routes:


| [**/algorithm/\[algorithm\]**](https://website-1m7ypjcve-thealgorithms.vercel.app/algorithm/[algorithm]) | [**/**](https://website-1m7ypjcve-thealgorithms.vercel.app/) |
|:-:|:-:|
|<a href="https://website-1m7ypjcve-thealgorithms.vercel.app/algorithm/[algorithm]">Screenshot of /algorithm/[algorithm]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/2n8-CXjvHW8u51Zdw1FNREPxUmgv-8oorAcldh3_1FuLBx3ENqOKPSw6voGfhjMWG1fJieAGbGoNbwlDlbl_rA.png">(view full size)</a> |<a href="https://website-1m7ypjcve-thealgorithms.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/hH4ZOXEHGPxotNCJrCGqpnQKm8SPW4p7zbFySAcK_tZKh92hJaA3hABNc4SzcXv2UHpsk2qEtcw0Ruug6rpVTw.png">(view full size)</a> |







Commit 2b3c9010b3ac071be347f36662c279368d014400 (https://website-1m7ypjcve-thealgorithms.vercel.app).

**Review by Panquesito7 — COMMENTED** [review]
I'm working on translating all the possible strings. 🙂

**Comment by maltejur** [comment]
how is this `rebase needed`? @Panquesito7

**Comment by Panquesito7** [comment]
> how is this `rebase needed`? @Panquesito7

There were merge conflicts previously, but it seems they are gone now.

**Review by Panquesito7 — DISMISSED** [review]
Great work, @maltejur! Seems to be working perfectly. Can be merged once merge conflicts are resolved. 👍 🎉

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
